# Generated by Django 5.1.7 on 2025-03-06 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('meeting', 'Meeting'), ('delivery', 'Delivery'), ('other', 'Other')], max_length=20)),
                ('client', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_form', models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit Card'), ('debit', 'Debit Card'), ('transfer', 'Bank Transfer')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
