# Generated by Django 5.1.7 on 2025-03-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='payment_form',
        ),
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.CharField(default='evento', max_length=255),
            preserve_default=False,
        ),
    ]
