# Generated by Django 5.1.7 on 2025-03-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_payment_form_event_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('15 anos', '15 Anos'), ('aniversário', 'aniversário'), ('batizado', 'Batizado'), ('bodas', 'Bodas'), ('casamento', 'Casamento'), ('chá', 'Chá'), ('formatura', 'Formatura'), ('empresarial', 'Empresarial'), ('outros', 'Outros')], max_length=20),
        ),
    ]
