# Generated by Django 5.1.7 on 2025-04-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('15 anos', '15 Anos'), ('aniversário', 'Aniversário'), ('batizado', 'Batizado'), ('bodas', 'Bodas'), ('casamento', 'Casamento'), ('chá', 'Chá'), ('formatura', 'Formatura'), ('empresarial', 'Empresarial'), ('outros', 'Outros')], max_length=20),
        ),
    ]
