# Generated by Django 5.1.7 on 2025-05-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_legacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='legacy',
            field=models.IntegerField(null=True),
        ),
    ]
