# Generated by Django 5.1.7 on 2025-05-17 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='company',
        ),
    ]
