# Generated by Django 5.1.7 on 2025-05-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_date_end_event_fiscal_doc_event_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='fiscal_doc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
