# Generated by Django 5.1.7 on 2025-05-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='legacy',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
