# Generated by Django 5.1.7 on 2025-05-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_email_alter_client_telephone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cpf_cnpj',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cpf_cnpj',
            field=models.CharField(max_length=18),
        ),
    ]
