# Generated by Django 5.1.7 on 2025-05-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_client_cpf_cnpj_alter_supplier_cpf_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='legacy',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
