# Generated by Django 5.1.7 on 2025-03-19 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_supplier'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='person',
        ),
        migrations.RemoveField(
            model_name='income',
            name='person',
        ),
        migrations.AddField(
            model_name='bill',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='clients.supplier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='clients.client'),
            preserve_default=False,
        ),
    ]
