# Generated by Django 5.1.7 on 2025-03-19 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_bill_person_remove_income_person_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='supplier',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='client',
            new_name='person',
        ),
    ]
