# Generated by Django 5.1.7 on 2025-04-22 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_costcenter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartaccount',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='payments.chartaccount'),
        ),
    ]
