# Generated by Django 5.1.7 on 2025-03-19 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_supplier'),
        ('payments', '0003_rename_supplier_bill_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client'),
        ),
        migrations.AddField(
            model_name='entry',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.supplier'),
        ),
    ]
