# Generated by Django 5.1.7 on 2025-04-27 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_migrate_payments_to_bill_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='object_id',
        ),
    ]
