# Generated by Django 5.1.7 on 2025-03-21 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_bankaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankAccount',
            new_name='Bank',
        ),
        migrations.AddField(
            model_name='bill',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.bank'),
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_doc_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.bank'),
        ),
        migrations.AddField(
            model_name='income',
            name='payment_doc_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
