# Generated by Django 5.1.7 on 2025-04-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accrual',
            name='doc_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
