# Generated by Django 5.1.7 on 2025-05-05 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_supplier'),
        ('payments', '0008_alter_accrual_doc_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='clients.supplier'),
        ),
        migrations.AlterField(
            model_name='eventallocation',
            name='accrual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_allocations', to='payments.accrual'),
        ),
        migrations.AlterField(
            model_name='income',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.bank'),
        ),
    ]
