# Generated by Django 5.1.7 on 2025-03-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_bill_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('em aberto', 'Em Aberto'), ('pago', 'Pago'), ('vencido', 'Vencido')], default='em aberto', max_length=10),
        ),
        migrations.AlterField(
            model_name='income',
            name='status',
            field=models.CharField(choices=[('em aberto', 'Em Aberto'), ('pago', 'Pago'), ('vencido', 'Vencido')], default='em aberto', max_length=10),
        ),
    ]
