# Generated by Django 5.1.7 on 2025-03-24 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_payment_person_content_type_payment_person_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='person_content_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='person_object_id',
        ),
    ]
