# Generated by Django 5.1.7 on 2025-05-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_bill_person_alter_eventallocation_accrual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='legacy',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
