# Generated by Django 5.1.7 on 2025-05-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_bank_legacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='legacy',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='legacy',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
