# Generated by Django 5.1.7 on 2025-05-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_alter_payment_bank_alter_payment_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='legacy',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='legacy',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='legacy',
            field=models.IntegerField(null=True),
        ),
    ]
