# Generated by Django 5.1.7 on 2025-03-25 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_payment_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='payment_doc_number',
        ),
        migrations.RemoveField(
            model_name='income',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='income',
            name='payment_doc_number',
        ),
    ]
