# Generated by Django 5.1.7 on 2025-05-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_banktransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='direction',
            field=models.CharField(blank=True, choices=[('entrada', 'Entrada'), ('saida', 'Saída')], help_text='Usado apenas para transferências internas', max_length=10, null=True),
        ),
    ]
