# Generated by Django 5.1.7 on 2025-05-12 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_payment_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='direction',
        ),
        migrations.DeleteModel(
            name='BankTransfer',
        ),
    ]
