# Generated by Django 5.1.7 on 2025-05-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_remove_payment_direction_delete_banktransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartaccount',
            name='group',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
