# Generated by Django 5.1.7 on 2025-03-25 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_alter_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='description',
        ),
    ]
