# Generated by Django 5.1.7 on 2025-04-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_remove_payment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('em aberto', 'Em Aberto'), ('pago', 'Pago'), ('vencido', 'Vencido'), ('parcial', 'Parcial')], default='em aberto', max_length=10),
        ),
        migrations.AlterField(
            model_name='income',
            name='status',
            field=models.CharField(choices=[('em aberto', 'Em Aberto'), ('pago', 'Pago'), ('vencido', 'Vencido'), ('parcial', 'Parcial')], default='em aberto', max_length=10),
        ),
    ]
