# Generated by Django 5.1.7 on 2025-05-17 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_alter_payment_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventallocation',
            name='accrual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_allocations', to='payments.accrual'),
        ),
    ]
