# Generated by Django 5.1.7 on 2025-05-17 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_alter_eventallocation_accrual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountallocation',
            name='company',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='company',
        ),
        migrations.RemoveField(
            model_name='eventallocation',
            name='company',
        ),
    ]
