# Generated by Django 5.1.7 on 2025-05-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_alter_payment_bank_alter_payment_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('pago', 'Pago')], default='pago', max_length=20),
        ),
    ]
