# Generated by Django 5.1.7 on 2025-05-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0024_payment_scheduled_date_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accrual',
            name='status',
            field=models.CharField(choices=[('em aberto', 'Em Aberto'), ('agendado', 'Agendado'), ('pago', 'Pago'), ('vencido', 'Vencido'), ('parcial', 'Parcial')], default='em aberto', max_length=10),
        ),
    ]
