# Generated by Django 5.1.7 on 2025-05-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0026_alter_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(),
        ),
    ]
