# Generated by Django 5.1.7 on 2025-05-18 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0027_alter_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='scheduled_date',
        ),
    ]
