# Generated by Django 5.1.7 on 2025-06-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0028_remove_payment_scheduled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='expected_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
